config/urls.py
import os

from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', core.views.signup, name='signup'),
    path("shows/", include("shows.urls", namespace="shows")),
    path('', core.views.index, name='index'),
    path('add_offer', core.views.add_offer, name='add_offer'),
    path('offer/<int:offer_id>', core.views.offer, name='offer'),
    path('offer_user/', core.views.offer_user, name='offer_user'),
    path('update_offer/<int:offer_id>', core.views.update_offer, name='update_offer'),
    path('fill_offer/<int:offer_id>', core.views.fill_offer, name='fill_offer'),
    path('unfill_offer/<int:offer_id>', core.views.unfill_offer, name='unfill_offer'),
    path('delete_offer/<int:offer_id>', core.views.delete_offer, name='delete_offer'),
    path('about', core.views.about, name='about'),
    path('tou', core.views.tou, name='tou'),
    path('announcement', core.views.announcement, name='announcement'),
    path('alert', core.views.alert, name='alert'),
    path("", include("promote.urls", namespace="promote")),
    path("__reload__/", include("django_browser_reload.urls")),
]

htmx_urlpatterns = [
    path('offer_search/', core.views.offer_search, name='offer_search'),
    path('offer/<int:offer_id>/contact_info', core.views.offer_contact_info, name='offer_contact_info'),
    path('offers/<int:page>', core.views.offers, name='offers'),
]

urlpatterns += htmx_urlpatterns

DEBUG = os.environ.get("DJANGO_DEBUG") == 'True'
if DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()

shows/urls.py
from django.urls import path
from . import views

app_name = "shows"

urlpatterns = [
    path("agenda/", views.agenda, name="agenda"),
    path("agenda/user/", views.agenda_user, name="agenda-user"),
    path("agenda/filter/", views.agenda_filter, name="agenda-filter"),
    path("play/<int:pk>/", views.play_detail, name="play_detail"),
    path('<int:pk>/add-representation/', views.add_representation, name='add_representation'),
    path("representation/partial/credit", views.get_representation_form_partial_credit, name="get_representation_credit"),
    path("representation/<int:pk>/delete/", views.delete_representation, name="delete_representation"),
    path("play/add/", views.add_play, name="add_play"),
    path("contributors/empty-row/", views.contributor_empty_row, name="contributor_empty_row"),
    path("plays/<int:pk>/edit/", views.edit_play, name="edit_play"),
    path("plays/<int:pk>/delete/", views.delete_play, name="delete_play"),
    path("repertoire/", views.repertoire, name="repertoire"),

]

core/models.py
# Create your models here.
from django.db import models
from django.db.models import CheckConstraint, Q
from django.db.models.fields import CharField

from accounts.models import CustomUser
import datetime

from django.utils import timezone

from moderation.models import ModerationResult


class Offer(models.Model):
    OFFER = 'offer'
    DEMAND = 'demand'
    PAID = 'paid'
    UNPAID = 'unpaid'
    MALE = 'male'
    FEMALE = 'female'
    OTHER = 'other'

    TYPE_CHOICES = [
        (OFFER, 'Offre'),
        (DEMAND, 'Demande'),
    ]

    # Rubriques principales du site
    ARTISTS_GROUPS = 'artists_groups'
    COURSES_TRAINING = 'courses_training'
    CALLS_EVENTS = 'calls_events'
    SERVICES_EQUIPMENT = 'services_equipment'

    SECTION_CHOICES = [
        (ARTISTS_GROUPS, 'Artistes & Groupes'),
        (COURSES_TRAINING, 'Cours & Formations'),
        (CALLS_EVENTS, 'Appels & Événements'),
        (SERVICES_EQUIPMENT, 'Services & Matériel'),
    ]

    CATEGORY_CHOICES = [
        (UNPAID, 'Bénévole'),
        (PAID, 'Rémunéré'),
    ]

    GENDER_CHOICES = [
        (OTHER, 'Non-Binaire'),
        (FEMALE, 'Femme'),
        (MALE, 'Homme'),
    ]

    type = models.CharField(
        max_length=255,
        choices=TYPE_CHOICES,
        default=OFFER,
    )

    section = models.CharField(
        max_length=255,
        choices=SECTION_CHOICES,
        default=ARTISTS_GROUPS)

    category = models.CharField(
        max_length=255,
        choices=CATEGORY_CHOICES,
        default=UNPAID,
    )

    title = models.CharField(max_length=50, null=False)
    summary = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=5000, blank=True)
    city = models.CharField(max_length=255, blank=True)
    min_age = models.PositiveIntegerField(null=True, blank=True)
    max_age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=255, choices=GENDER_CHOICES, default=None, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    filled = models.BooleanField(default=False)
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    show_author_mail = models.BooleanField(default=False)
    contact_name = models.CharField(max_length=255, null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)
    contact_phone = models.CharField(max_length=255, null=True, blank=True)
    contact_website = models.URLField(null=True, blank=True)
    contact_details = models.TextField(null=True, blank=True)
    moderation = models.ForeignKey(ModerationResult, null=True, blank=True, on_delete=models.SET_NULL, related_name="offers")


    def __str__(self):
        return f'{self.title} - {self.author} - {self.created_on.strftime("%Y-%m-%d, %H:%M")}'

    @property
    def recent(self):
        offer_date = self.created_on
        threshold = timezone.now() - datetime.timedelta(weeks=1)
        return offer_date > threshold


    def get_moderation_text(self) -> str:
        """
        Retourne une chaîne de texte contenant toutes les informations importantes de l'annonce,
        formatée pour être soumise à la modération de contenu.
        """
        details = [
            f"Type: {self.get_type_display()}",
            f"Catégorie: {self.get_category_display()}",
            f"Titre: {self.title}",
            f"Résumé: {self.summary}",
            f"Description: {self.description}",
            f"Ville: {self.city}" if self.city else None,
            f"Âge minimum: {self.min_age}" if self.min_age else None,
            f"Âge maximum: {self.max_age}" if self.max_age else None,
            f"Genre: {self.get_gender_display()}" if self.gender else None,
        ]

        # Filtrer les valeurs None et joindre les éléments par une nouvelle ligne
        return "\n".join(filter(None, details))

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django_email_blacklist import DisposableEmailChecker
# from turnstile.fields import TurnstileField

from accounts.models import CustomUser
from core.models import Offer

class OfferForm(ModelForm):
    # turnstile = TurnstileField()

    class Meta:
        model = Offer
        fields = ['type',
                  'section',
                  'category',
                  'title',
                  'summary',
                  'description',
                  'city',
                  'min_age',
                  'max_age',
                  'gender',
                  'show_author_mail',
                  'contact_name',
                  'contact_email',
                  'contact_phone',
                  'contact_website',
                  'contact_details',
                  ]
        labels = {
            'type': "Type d'annonce",
            'section': 'Rubrique',
            'category': 'Rémunération',
            'title': "Titre de l'annonce",
            'summary': 'Résumé',
            'city': 'Ville',
            'min_age': 'Âge apparent minimal',
            'max_age': 'Âge apparent maximal',
            'gender': 'Genre',
            'show_author_mail': 'Afficher Email utilisateur',
            'contact_name': 'Nom du contact',
            'contact_email': 'Email',
            'contact_phone': 'Numéro de téléphone',
            'contact_website': 'Site internet',
            'contact_details': 'Infos supplémentaires',
        }



class SignUpForm(UserCreationForm):
    # turnstile = TurnstileField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = 'Le mot doit faire plus de 8 caractères, ne pas être un mot de passe trop commun et ne pas être entièrement numérique.'

    def clean_email(self):
        email = self.cleaned_data['email']
        email_checker = DisposableEmailChecker()
        if email_checker.is_disposable(email):
            self.add_error('email', 'Utilisez une adresse email non-jetable svp')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            self.add_error('password2', "Les deux mots de passe sont différents")
        return password2

core/views.py
import os

from datetime import date

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.db.models import F


from core.forms import OfferForm, SignUpForm
from core.models import Offer
from moderation.services import moderate_text
from promote.models import Promote


# Create your views here.
def index(request):
    all_offers = Offer.objects.select_related('moderation').filter(filled=False).filter(Q(moderation__isnull=True) | Q(moderation__passed=True)).order_by('-created_on')

    today = date.today()
    promo = Promote.objects.filter(
        start_date__lte=today,
        end_date__gte=today
    ).order_by('?').first()

    # promo = Promote.objects.get(slug="hotel-isole-romantique-pres-de-paris")

    if promo:
        Promote.objects.filter(pk=promo.pk).update(
            impression_count=F("impression_count") + 1
        )
    else:
        promo = Promote.objects.filter(slug__exact='your-ad').first()

    return render(request, 'core/index.html', {
        'all_offers': all_offers[0:20],
        'page': 1,
        'page_next': 2,
        'promo': promo,
    })

def offers(request, page: int):
    all_offers = Offer.objects.select_related('moderation').filter(filled=False).filter(
        Q(moderation__isnull=True) | Q(moderation__passed=True)).order_by('-created_on')
    return render(request, 'core/partials/offers_partials.html', {
        'all_offers': all_offers[(page-1)*20:(page)*20],
        'page': page,
        'page_next': page+1,
    })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect("index")
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def add_offer(request):
    MAPBOX_ACCESS_TOKEN = os.environ.get("MAPBOX_ACCESS_TOKEN")
    # with open('blogApp/static/fr_cities.json') as f:
    #     fr_cities = json.load(f)
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.author = request.user
            moderation_result = moderate_text(offer.get_moderation_text())
            offer.moderation = moderation_result
            offer.save()
            offer_id = offer.id
            return redirect('offer', offer_id=offer_id)
    else:
        form = OfferForm()
    return render(request,
                  'core/add_offer.html',
                  {'form': form, 'offer_id': -1, 'MAPBOX_ACCESS_TOKEN': MAPBOX_ACCESS_TOKEN})


@login_required
def update_offer(request, offer_id: int):
    MAPBOX_ACCESS_TOKEN = os.environ.get("MAPBOX_ACCESS_TOKEN")
    if request.method == 'POST':
        offer = get_object_or_404(Offer, id=offer_id)
        if offer.author != request.user:
            return redirect('offer', offer_id=offer_id)
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            offer = form.save(commit=False)
            moderation_result = moderate_text(offer.get_moderation_text())
            offer.moderation = moderation_result
            offer.save()
            return redirect('offer', offer_id=offer_id)
    else:
        offer = get_object_or_404(Offer, id=offer_id)
        if offer.author != request.user:
            return redirect('offer', offer_id=offer_id)
        form = OfferForm(instance=offer)
    return render(request,
                  'core/add_offer.html',
                  {'form': form, 'offer_id': offer_id, 'MAPBOX_ACCESS_TOKEN': MAPBOX_ACCESS_TOKEN})


@login_required
def delete_offer(request, offer_id: int):
    if request.user.id == Offer.objects.get(pk=offer_id).author.id:
        Offer.objects.get(pk=offer_id).delete()
        return redirect('index')
    else:
        return redirect('index')


@login_required
def fill_offer(request, offer_id: int):
    if request.user.id == Offer.objects.get(pk=offer_id).author.id:
        offer = get_object_or_404(Offer, pk=offer_id)
        offer.filled = True
        offer.save()
        return redirect('offer', offer_id=offer_id)
    else:
        return redirect('offer', offer_id=offer_id)


@login_required
def unfill_offer(request, offer_id: int):
    if request.user.id == Offer.objects.get(pk=offer_id).author.id:
        offer = get_object_or_404(Offer, pk=offer_id)
        offer.filled = False
        offer.save()
        return redirect('offer', offer_id=offer_id)
    else:
        return redirect('offer', offer_id=offer_id)



def offer(request, offer_id: int):
    offer = get_object_or_404(Offer, pk=offer_id)
    if offer.moderation and not offer.moderation.passed:
        return render(request, 'core/offer_moderation_failed.html', {'offer': offer})
    return render(request, 'core/offer.html', {'offer': offer})


def offer_search(request):
    search_data = request.POST

    # Champs du formulaire
    search_query = search_data.get('search', '').strip()
    section = search_data.get('section')
    offer_type = search_data.get('type')
    category = search_data.get('category')

    # Base queryset
    results = Offer.objects.select_related('moderation').filter(filled=False).filter(
        Q(moderation__isnull=True) | Q(moderation__passed=True)
    )

    # Filtres dynamiques
    if search_query:
        results = results.filter(
            Q(title__icontains=search_query) |
            Q(summary__icontains=search_query) |
            Q(city__icontains=search_query)
        )

    if section:
        results = results.filter(section=section)

    if offer_type:
        results = results.filter(type=offer_type)

    if category:
        results = results.filter(category=category)

    context = {
        'all_offers': results.order_by('-created_on')
    }

    return render(request, 'core/partials/offers_partials.html', context)


@login_required
def offer_user(request):
    user_offers = Offer.objects.select_related('moderation').filter(author=request.user.id)
    context = {
        'all_offers': user_offers.order_by('-created_on')
    }
    return render(request, 'core/offer_user.html', context)



def offer_contact_info(request, offer_id: int):
    offer = get_object_or_404(Offer, pk=offer_id)
    return render(request, 'core/partials/offer_contact_info.html', {'offer': offer})


def about(request):
    return render(request, 'core/about.html')


def tou(request):
    return render(request, 'core/tou.html')

def announcement(request):
    return render(request, 'core/announcement.html')


def alert(request):
    return render(request, 'core/alert.html')

core/templates/core/forms/form_offer_l2.html
{% if offer_id == -1 %}
<form action="{% url 'add_offer' %}" method="post">
{% else %}
<form action="{% url 'update_offer' offer_id %}" method="post">
{% endif %}
{% csrf_token %}
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
        <div class="form-control">
            <label class="label" for="id_type">{{ form.type.label }}*</label>
            <select class="select select-bordered" name="type" id="id_type">
                <option value="offer" {% if form.instance.type == 'offer' %}selected{% elif form.instance.type == 'demand' %} {% else %}selected{% endif %}>Troupe cherche comédien.ne</option>
                <option value="demand" {% if form.instance.type == 'demand' %}selected{% endif %}>Comédien.ne cherche troupe</option>
            </select>
        </div>
        <div class="form-control">
            <label class="label" for="id_category">{{ form.category.label }}*</label>
            <select class="select select-bordered" name="category" id="id_category">
                <option value="unpaid" {% if form.instance.category == 'unpaid' %}selected{% elif form.instance.category == 'paid' %} {% else %}selected{% endif %}>Bénévole</option>
                <option value="paid" {% if form.instance.category == 'paid' %} selected{% endif %}>Rémunéré</option>
            </select>
        </div>
    </div>
    <div class="form-control">
        <label class="label" for="id_title">{{ form.title.label }}*</label>
        <input class="input input-bordered" type="text" name="title" maxlength="50" required id="id_title" value="{{ form.instance.title }}">
    </div>
    <div class="form-control">
        <label class="label" for="id_summary">{{ form.summary.label }}*</label>
        <input class="input input-bordered" type="text" name="summary" maxlength="255" required id="id_summary" value="{{ form.instance.summary }}">
    </div>
    <div class="form-control">
        <label class="label" for="id_description">{{ form.description.label }}</label>
        <textarea class="textarea textarea-bordered" name="description" rows="5" maxlength="5000" id="id_description">
                {{ form.instance.description }}
            </textarea>
    </div>
    <div class="form-control">
        <label class="label" for="id_city">{{ form.city.label }}</label>
        <input class="input input-bordered" type="text" name="city" maxlength="255" id="id_city" value="{{ form.instance.city }}">
    </div>
    <div class="grid grid-cols-2 md:grid-cols-3 gap-2">
        <div class="form-control">
            <label class="label" for="id_min_age">{{ form.min_age.label }}</label>
            <input class="input input-bordered" type="number" name="min_age" min="0" id="id_min_age" value="{{ form.instance.min_age }}">
            {{ form.min_age.errors }}
        </div>
        <div class="form-control">
            <label class="label" for="id_max_age">{{ form.max_age.label }}</label>
            <input class="input input-bordered" type="number" name="max_age" min="0" id="id_max_age"  value="{{ form.instance.max_age }}">
            <p>{{ form.max_age.errors }}</p>
        </div>
        <div class="form-control col-span-2 md:col-span-1">
            <label class="label" for="id_gender">{{ form.gender.label }}</label>
            <select class="select select-bordered" name="gender" id="id_gender">
                <option value="" {% if form.instance.gender == '' %}selected{% elif form.instance.type == 'other' %} {% elif form.instance.type == 'female' %} {% elif form.instance.type == 'male' %} {% else %}selected{% endif %}>---------</option>
                <option value="other" {% if form.instance.gender == 'other' %}selected{% else %} {% endif %}>Non-Binaire</option>
                <option value="female" {% if form.instance.gender == 'female' %}selected{% else %} {% endif %}>Femme</option>
                <option value="male" {% if form.instance.gender == 'male' %}selected{% else %} {% endif %}>Homme</option>
            </select>
        </div>
    </div>
    <div class="form-control flex flex-row gap-2 items-center">
        <label class="label" for="id_show_author_mail">{{ form.show_author_mail.label }}</label>
        <input class="toggle" name="show_author_mail" id="id_show_author_mail" type="checkbox" {% if form.instance.show_author_mail %}checked{% else %}{% endif %}>
    </div>
    <input class="btn btn-block mt-2" type="submit" value="{% if offer_id == -1 %}Déposer{% else %}Modifier{% endif %} mon annonce">
</form>